### PARKING ###
PARKING:
  klt_params:
    winSize: [31, 31]
    maxLevel: 3
    criteria:
      - TERM_CRITERIA_EPS_OR_COUNT
      - 30
      - 6
    minEigThreshold: 0.01

  sift_params:
    threshold: 0.8

  init_params:
    baseline_frame_indices: [0, 13] # frames used to init pointcloud
    matcher: 1 # KLT = 0, SIFT = 1
    ransac_params_F:
      threshold: 0.1
      confidence: 0.999
      num_iterations: 10000
    max_depth_distance: 50
  
  continuous_params:
    angle_threshold: 0.0436 # calculate one that is reasonable; this angle is an indirect measure of the baseline
    max_track_length: 10 # for memory efficiency
    min_track_length: 3
    pnp_ransac_params:
      threshold: 1
      confidence: 0.99
      num_iterations: 10000
    same_keypoints_threshold: 20
    max_depth_distance: 50

### KITTI ###
KITTI:
  klt_params:
    winSize: [21, 21]
    maxLevel: 8
    criteria:
      - TERM_CRITERIA_EPS_OR_COUNT
      - 10
      - 0.001
    minEigThreshold: 0.01
  sift_params:
    threshold: 0.8

  init_params:
    baseline_frame_indices: [0, 10] # frames used to init pointcloud
    matcher: 1 # KLT = 0, SIFT = 1
    ransac_params_F:
      threshold: 0.1
      confidence: 0.9999
      num_iterations: 100
    max_depth_distance: 50
  
  continuous_params:
    angle_threshold: 0.0436 # calculate one that is reasonable; this angle is an indirect measure of the baseline
    max_track_length: 10 # for memory efficiency
    min_track_length: 6 
    pnp_ransac_params:
      threshold: 1
      confidence: 0.9999
      num_iterations: 100
    same_keypoints_threshold: 2
    max_depth_distance: 50

### MALAGA ####
MALAGA:
  klt_params:
    winSize: [21, 21]
    maxLevel: 8
    criteria:
      - TERM_CRITERIA_EPS_OR_COUNT
      - 10
      - 0.001
    minEigThreshold: 0.01

  sift_params:
    threshold: 0.8

  init_params:
    baseline_frame_indices: [0, 3] # frames used to init pointcloud
    matcher: 1 # KLT = 0, SIFT = 1
    ransac_params_F:
      threshold: 0.1
      confidence: 0.9999
      num_iterations: 100
    max_depth_distance: 50
  
  continuous_params:
    angle_threshold: 0.0436 # calculate one that is reasonable; this angle is an indirect measure of the baseline
    max_track_length: 10 # for memory efficiency
    min_track_length: 6 
    pnp_ransac_params:
      threshold: 1
      confidence: 0.9999
      num_iterations: 100
    same_keypoints_threshold: 1
    max_depth_distance: 50